LangString addOrReinstall ${LANG_JAPANESE} "構成を追加または再インストール"
LangString alreadyInstalled ${LANG_JAPANESE} "すでにインストールされています"
LangString alreadyInstalledLong ${LANG_JAPANESE} "${PRODUCTNAME} ${VERSION} はすでにインストールされています。実行する操作を選び、「次へ」を押してください。"
LangString appRunning ${LANG_JAPANESE} "{{product_name}} が起動中です。先に閉じてから、もう一度お試しください。"
LangString appRunningOkKill ${LANG_JAPANESE} "{{product_name}} が起動中です。$\nOK を押すと終了してから続行します。"
LangString chooseMaintenanceOption ${LANG_JAPANESE} "実行するメンテナンス操作を選んでください。"
LangString choowHowToInstall ${LANG_JAPANESE} "${PRODUCTNAME} のインストール方法を選んでください。"
LangString createDesktop ${LANG_JAPANESE} "デスクトップにショートカットを作成"
LangString dontUninstall ${LANG_JAPANESE} "アンインストールしない"
LangString dontUninstallDowngrade ${LANG_JAPANESE} "アンインストールしない（このインストーラでは、アンインストールなしのダウングレードはできません）"
LangString failedToKillApp ${LANG_JAPANESE} "{{product_name}} を終了できませんでした。手動で閉じてから、もう一度お試しください。"
LangString installingWebview2 ${LANG_JAPANESE} "必要な WebView2 を準備しています..."
LangString newerVersionInstalled ${LANG_JAPANESE} "より新しい ${PRODUCTNAME} がすでにインストールされています。古い版を入れる前に、現在の版を削除することをおすすめします。操作を選び、「次へ」を押してください。"
LangString older ${LANG_JAPANESE} "古い"
LangString olderOrUnknownVersionInstalled ${LANG_JAPANESE} "${PRODUCTNAME} の $R4 バージョンが見つかりました。新しく入れ直す前に、現在の版を削除することをおすすめします。操作を選び、「次へ」を押してください。"
LangString silentDowngrades ${LANG_JAPANESE} "このインストーラではダウングレードできません。サイレントインストールでは続行できないため、通常の画面から操作してください。$\n"
LangString unableToUninstall ${LANG_JAPANESE} "アンインストールできませんでした。"
LangString uninstallApp ${LANG_JAPANESE} "${PRODUCTNAME} をアンインストール"
LangString uninstallBeforeInstalling ${LANG_JAPANESE} "インストール前にアンインストール"
LangString unknown ${LANG_JAPANESE} "不明"
LangString webview2AbortError ${LANG_JAPANESE} "WebView2 の準備に失敗しました。このアプリの起動に必要です。インストーラを再実行してください。"
LangString webview2DownloadError ${LANG_JAPANESE} "エラー: WebView2 のダウンロードに失敗しました - $0"
LangString webview2DownloadSuccess ${LANG_JAPANESE} "WebView2 のダウンロードが完了しました。"
LangString webview2Downloading ${LANG_JAPANESE} "WebView2 をダウンロードしています..."
LangString webview2InstallError ${LANG_JAPANESE} "エラー: WebView2 のインストールに失敗しました。終了コード: $1"
LangString webview2InstallSuccess ${LANG_JAPANESE} "WebView2 の準備が完了しました。"
LangString deleteAppData ${LANG_JAPANESE} "アプリの設定データも削除する"
